osx_image: xcode12
language: objective-c
notifications:
  email: false
branches:
  only:
    - main
before_install:
  - make install-aws-cli
  - make config-aws-s3
script:
  - fastlane matchappstore --verbose
  - fastlane beta --verbose