osx_image: xcode12
language: objective-c
script: xctool -workspace OutToday.xcworkspace -scheme OutToday

stages:
  jobs:
    include:
    - stage: deploy
      if: tag IS present
      branches:
        only:
        - master
      xcode_project: OutToday.xcodeproj
      xcode_scheme: OutToday
      xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone X
      before_install:
        - brew install applesimutils
        - gem install rake
        - brew install xctool
      script:
        - fastlane beta