stages:
  jobs:
    include:
    - stage: deploy
      if: tag IS present
      branches:
        only:
        - master
      language: objective-c
      gemfile: Gemfile
      os: osx
      osx_image: xcode12.2
      install:
        - bundle
      script:
        - fastlane beta