osx_image: xcode12
language: objective-c
notifications:
  email: false
branches:
  only:
    - main
script: xcodebuild -workspace OutToday.xcworkspace -scheme OutToday -allowProvisioningUpdates
xcode_project: OutToday.xcodeproj
xcode_scheme: OutToday
xcode_destination: platform=iOS SimulatOS=14.0,name=iPhone X
script:
  - fastlane beta