osx_image: xcode12
language: objective-c
notifications:
  email: false
branches:
  only:
    - main
before_install:
  - make install-aws-cli
  - make config-aws-s3
  - make get-app-store-connect-file
script:
  - fastlane matchappstore
  - fastlane beta