osx_image: xcode12
language: objective-c
notifications:
  email: false
branches:
  only:
    - main
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: xcodebuild -workspace OutToday.xcworkspace -scheme OutToday -allowProvisioningUpdates
xcode_project: OutToday.xcodeproj
xcode_scheme: OutToday
xcode_destination: platform=iOS SimulatOS=14.0,name=iPhone X
script:
  - fastlane beta --verbose