setup_travis
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :matchappstore do
    match(
      app_identifier: "com.nataliabraz.OutToday.OutTodayWidget",
      type: "appstore",
    )
  end
  lane :beta do
    match(type: "appstore")
    increment_build_number(build_number: "13")
    build_app(scheme: "OutToday")
    pilot(api_key_path: ENV["PILOT_API_KEY_PATH"])
  end
end
