# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", git_private_key: "a040a6bd395790f8a898e5a5e85408334e73a23a")
    increment_build_number(xcodeproj: "OutToday.xcodeproj")
    build_app(scheme: "OutToday")
    upload_to_testflight
  end
end
